version: "3"
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  web:
    # image: servicr
    build: .
    volumes:
      - ./:/app  
    ports:
      - "3000:3000"
    links:
      - db
    command: "yarn dev"
    # replace username/repo:tag with your name and image details
    # deploy:
    #   replicas: 5
    #   resources:
    #     limits:
    #       cpus: "0.1"
    #       memory: 50M
    #   restart_policy:
    #     condition: on-failure

    networks:
      - webnet
networks:
  webnet:
